.meteor/packages, .meteor/versions, client/components/header/Header.js
* `meteor add nathantreid:static-assets`
(idea from
https://forums.meteor.com/t/static-assets-compiler-released-import-images-etc-into-your-js-files/41781)
* Uncomment SVG logo import/include logic in Header.js
=> Make the logo work again

.dockerignore, Dockerfile, README.md, docker-compose.yml
Basé sur https://hub.docker.com/r/jshimko/meteor-launchpad/
=> Dockerisation de l'app

app/client/ui/components/sites/Add.js, app/client/ui/components/tags/Tag.js
Amélioration de la gestion des msg utilisateurs : le msg disparaît lorsque : 
- on sélectionne un autre élément (onBlur)
- on modifie la valeur d'un élément (onChange)
=> improve msg

app/both/collections.js, app/server/indexes.js, app/server/main.js
Get only sites with status : created
=> Active sites only for API sites

app/both/collections.js, app/server/main.js
Sélectionne tous les sites qui sont créés ou sites "Non WordPress"
=> Sélectionner aussi les sites non WordPress

app/client/ui/components/sites/List.js
Ajouter les tags dans l'export
=> Add tags to export

ansible/roles/epfl.wp-veritas/vars/main.yml, app/.meteor/versions, app/both/collections.js, app/both/methods.js, app/client/ui/components/CustomFields.js, app/client/ui/components/sites/Add.js, app/server/import-data.js
Ajout d'un champ pour permettre à un site d'être soumis aux tests de ressenti !
=> add field to user experience

ansible/roles/epfl.wp-veritas/vars/main.yml, app/client/ui/components/sites/Search.js, app/package-lock.json, app/package.json
Améliore la recherche des instances.
Les cas traités
- Si le site n'est pas dans la source de vérité : ex https://google.com
- Si le site est un site dans la source de vérité mais avec le statut **non WordPress**
- Si le site est un site dans la source de vérité mais avec le statut **créé**
- Si le site est un site avec le statut autre que **créé** ou **non WordPress**
=> improve research of instance WP

ansible/roles/epfl.wp-veritas/vars/main.yml, app/both/collections.js, app/both/methods.js, app/client/ui/components/sites/Add.js
- Ajout d'un slug par site afin d'offrir un libellé court pour identifer chaque site dans l'interface du ressenti.
- Correction d'un bug lors de la mise à jour d'un site pour assurer l'unicité des URLs.
=> Add slug + fix bug unique URL

app/server/main.js, app/server/rest-api.js, app/server/tequila-config.js
Ajout de l'entry point /tags et /tags/:id
avec la possibilité de filtrer par type de tags : 
/api/v1/tags?type=field-of-research
=> Add new entrypoint API

ansible/roles/epfl.wp-veritas/vars/main.yml, app/imports/api/collections.js, app/imports/api/methods.js, app/imports/ui/components/sites/Add.jsx, app/server/import-data.js, app/server/main.js
- Suppression du champ "Faculty"
- Mise à jour du champ thème : Si la valeur vaut "2018" alors setté à "epfl"
=> Delete faculty field + update theme all theme '2018' to 'epfl'

ansible/roles/epfl.wp-veritas/vars/main.yml, app/imports/api/methods.js, app/imports/ui/components/sites/Search.jsx, app/package-lock.json, app/package.json, app/server/main.js
- Modification du msg user lorsque l'URL saisi n'est pas un site WP géré par la vpsi.
- Affichage du nom de l'unité en faisant une requête LDAP
=> Ldap query to display unit name

README.md, ansible/roles/epfl.wp-veritas/vars/main.yml, app/imports/ui/components/header/Header.jsx
Ajout du numéro de version dans le Header => pratique pour vérifier que la nouvelle version est bien passée en prod
=> Update version number 1.0.0

cli/index.js, cli/lib/command.js, cli/lib/db-helper.js, cli/lib/helpers.js
- Charger les datas de test soit sur localhost soit sur test
- Adapter le code après le déplacement de la DB de test dans l'infra de test de c2c
- refactoring
=> Cli load tests data

README.md
=> Add travis CI badge

app/imports/ui/components/footer/Footer.jsx
=> [feature] Add github sources in the footer

cli/index.js, cli/lib/command.js, cli/lib/config.sample.js, cli/lib/db-helper.js, cli/lib/helpers.js, cli/package-lock.json, cli/package.json
If accepted this PR will mostly :
- add a default config file ;
- allows to parametrize local host and port for mongoDB
- ensure that mongodb is present in package.json
=> [feature] Improvments in wp-veritas-cli

app/imports/ui/App.jsx, app/server/import-data.js
Port :3000 is removed and now check for http.//localhost url only.
=> [fix] allow ops to specify another localhost port

Makefile, ansible/roles/epfl.wp-veritas/vars/main.yml, app/imports/api/methods/sites.js, app/imports/api/telegram.js, app/imports/ui/components/header/Header.jsx
Cette PR a pour but d'envoyer les messages Telegram pour la suppression ou la creation d'un site seulement dans le cas des sites dans notre infra VPSI et pas pour les sites présents dans wp-veritas mais en dehors de notre infra VPSI.
=> [fix] Send telegram msg only for site inside infra

Makefile, ansible/hosts-dev, ansible/hosts-prod, ansible/hosts-test, ansible/roles/epfl.wp-veritas/vars/main.yml, app/imports/api/utils.js, app/imports/ui/components/header/Header.jsx, app/server/main.js, cli/index.js, cli/lib/command.js, cli/lib/db-helper.js
This is a "dev-support" feature that disable the Tequlia jam when developing the app (if the environment is set to "LOCALHOST".
=> [feature] disable Tequila when environment is "LOCALHOST"

ansible/roles/epfl.wp-veritas/vars/main.yml, app/imports/ui/components/header/Header.jsx, app/imports/ui/components/sites/Search.jsx, app/package-lock.json, app/package.json
Le service desk a besoin de pouvoir savoir pour une URL quelle est l'instance WP.
Cette fonctionnalité a été améliorée et debuggée
Tickert SNOW INC0372398
=> Search WP instance by URL

ansible/roles/epfl.wp-veritas/vars/main.yml, app/imports/ui/components/header/Header.jsx, app/package-lock.json, app/package.json, app/server/api/sites.js, app/server/api/tests/api-sites.test.js, app/server/api/utils.js, app/server/main.js
=> [feature] Add ansible host pattern to Rest API

ansible/roles/epfl.wp-veritas/vars/main.yml, app/imports/api/methods/sites.js, app/imports/api/methods/tests/sites.test.js, app/imports/ui/components/header/Header.jsx, app/imports/ui/components/sites/Search.jsx, app/package-lock.json, app/package.json, app/server/api/sites.js, app/server/api/tests/api-sites.test.js, app/server/api/utils.js, app/server/import-data.js, app/server/main.js
Le but de cette PR est que:
- chaque URL des sites se termine avec un slash.
- la recherche d'instance en fonction d'une URL soit ok avec le slash final
- la validation d'un site soit ok avec le slash final
#123
=> [fix] Add trailing slash of sites URL

ansible/roles/epfl.wp-veritas/vars/main.yml, app/imports/api/methods/utils.js, app/imports/ui/components/header/Header.jsx, app/package-lock.json, app/package.json, app/server/main.js
Dans wp-veritas, il n'y a plus de sous-catégories
=> [clean] clean subcategories

app/imports/api/methods/sites.js, app/imports/api/telegram.js
When using the Telegram.sendMessage() method, it's now possible to deactivate the web preview or the notification as specified in the [Telegram API documentation](https://core.telegram.org/bots/api).
=> [feature] implements `disable_web_page_preview` and `disable_notifications`

app/imports/ui/components/sites/LastChange.jsx, app/imports/ui/components/sites/Search.jsx, app/package-lock.json, app/package.json
New feature that displays the user that made last change of a website and the date of the change
=> [feature] Add WPLastChange

app/imports/ui/components/admin/Trash.jsx, app/imports/ui/components/professors/Professor.jsx, app/imports/ui/components/sites/Add.jsx, app/imports/ui/components/sites/List.jsx, app/imports/ui/components/tags/Tag.jsx
This should fix the issue with the grayed-out buttons observed by Natalie.
=> [fix] more not-a-callback-anymore situations

app/imports/ui/components/sites/List.jsx
=> [fix] Language code for Greek

Dockerfile, Makefile
Unnecessary since jam:method 1.6.0
=> [chore] Remove meteor-method fork

app/imports/ui/components/sites/List.jsx
=> [fix] Prevent enter key from submitting

docker-compose-dev.yml, docker-compose.yml
The attribute `version` is obsolete.
=> [chore] Remove attribute `version`

app/imports/api/methods/rate-limiting.js, app/package-lock.json, app/package.json
=> [chore] Remove underscore package

app/server/rest/sites.js
=> [fix] MongoDB regex flag

app/package-lock.json, app/package.json
=> [chore] Remove url-parse package

cli/package-lock.json, cli/package.json
=> [chore] Remove colors package

ansible/inventory/prod.yml, ansible/inventory/test.yml, app/client/index.css, app/imports/ui/components/admin/Admin.jsx, app/imports/ui/components/sites/Add.jsx, app/imports/ui/components/sites/List.jsx, app/package-lock.json, app/package.json
This is based on the `Type.schema` attribute, meaning this is the same  logic than a site using the `external` schema within showing the `LAMP`  type.
=> [feature] Add the LAMP type

app/imports/ui/components/sites/LastModifications.jsx, app/imports/ui/components/sites/Search.jsx
https://erpdev.atlassian.net/browse/WPN-406
=> [feature] Display information on the last 5 modified pages of a given website on the search page
